### ISSUE TITLE
Needs a package.json

### ISSUE THREAD

**Issue by lvivier** [lvivier/uploader#5]
This package should work with [browserify](http://browserify.org/) now that [component is EOL](https://github.com/componentjs/component/issues/639).

Component automatically packages CSS into a separate bundle; in Browserify modules CSS is handled with transforms and added to the DOM at run time.

Intro to Browserify: [substack/browserify-handbook](https://github.com/substack/browserify-handbook)

- [x] Create a package.json with info from component.json
- [x] Use [browserify-css](https://www.npmjs.com/package/browserify-css) (devDependency) to handle CSS
- [x] Add [configuration to package.json](https://github.com/substack/browserify-handbook#browserifytransform-field) so browserify will use the transform automatically
- [x] Confirm example works (you'll have to remove the build.css line)
- [x] Update readme
- [x] After PR is in, ping @lvivier to tag a release

**Comment by slajax** [comment]
@lvivier is there anything else that needs to be done here other then add the package.json? What was the catalyst for this OOC? A little more info please and then I can assign it to @CalvinScott to pick up after he helps Colin with import mapping.

**Comment by lvivier** [comment]
@slajax just want to move off component 100%, if @CalvinScott wants to take this on I'll add a description of how to achieve this w/straight browserify

**Comment by CalvinScott** [comment]
I'll start looking into it right now
